name: Json(Beta)

on:
  schedule:
    - cron: '0 0 * * *'  # Run once a day at midnight UTC
  workflow_dispatch:      # Allow manual triggers

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Grant execute permissions
        run: chmod +x generate_beta.sh

      - name: Generate JSON file
        run: ./generate_beta.sh

      - name: Commit if changed
        run: |
          git config --global user.name "Vladyslav"
          git config --global user.email "56305121+vladrevers@users.noreply.github.com"
          git add pif_beta.json
          git diff --quiet --staged || git commit -m "Update pif_beta.json" && git push
